### DISCUSSION TITLE
I don't know how to modify the URL in the config/config.yaml

### DISCUSSION THREAD

**Discussion by xodhks3038** [giongto35/cloud-game#388] [Q&A]
It was quite interesting to see the cloud-game of giongto35.
Thus, it was confirmed that the test was completed successfully using the make command.
The next thing was to put it on the docker container.
I didn't find it particularly difficult to upload, but there was one problem.

URL from config.yaml.

The error I received was "404 Not Found" on the "https://github.com/sergystepanov/libretro-spiegel/blob/main/linux/x86_64/latest/mupen64plus_next_libretro.so.zip?raw=true" page.
So when I looked up the contents, the route was changed.
It's the https://github.com/sergystepanov/libretro-spiegel/blob/main/linux/armv7-neon-hf/latest/mupen64plus_next_libretro.so.zip route, but when I tried to change it, there was one more problem.

In the config.yaml file, only "https://github.com/sergystepanov/libretro-spiegel/blob/main" is defined.
It is not easy to find what is further defined.

If you know how to change it, please give me an answer.

**Comment by sergystepanov** [comment]
There are a couple of parameters in regard to the Libretro cores auto-downloader. If it's easier, you can disable this (`libretro.cores.repo.sync: false`) function completely and copy all your libs manually into the `assets/cores` folder.

With the `repo` part of the config file, we set two places where the auto-downloader will be searching for Libretro cores or more precisely Libretro emulators compiled for different operating systems and processor architectures. It is the main and secondary (alt[ernative]) repositories. The main repository is the first and main place for finding all the cores just like RetroArch finds and downloads its cores. And the second repository's sole purpose is to provide a place where you can store all your custom, tested, or absent from the main repo cores, which will be used if a core is not found in the main repo (i.e. official Libretro repository doesn't have N64 cores for the ARM processors). But there is `a hack` parameter set for N64 cores in the `libretro.cores.list.n64.altRepo` which inverts the order of repositories, so for n64 it searches in the alt repo first and after that in the main (will be useful, for example, when a core is broken for your system in the official repo). Set it to false if you want to use the main repo first.

URL params from the config are not full addresses, they are just the base URLs. The full URL is built automatically depending on your OS and CPU arch and this auto-guessing part it's not configurable: 
"https://github.com/sergystepanov/libretro-spiegel/blob/main/[OS]/[CPU arch]/latest/core-name".
Disregarding the order of repos it should find and download a core for your OS/CPU unless it can't guess your CPU/OS properly.
Take a look at this code https://github.com/giongto35/cloud-game/blob/3bd959b4ef53cffbddad6d605a036d085aa48969/pkg/worker/emulator/libretro/core.go and compare it to your
GOOS:GOARCH keys (run `go env` in the console of the system where the apps are running to see these params).

Here is all params for auto-downloader:
```yaml
libretro:
    # ...
    cores:
      # ...
      # Config params for Libretro cores repository,
      # available types are:
      #   - buildbot (the default Libretro nightly repository)
      #   - github (GitHub raw repository with a similar structure to buildbot)
      #   - raw (just a link to a zip file extracted as is)
      repo:
        # enable auto-download for the list of cores (list->lib)
        sync: true
        # ...
        main:
          type: buildbot
          url: https://buildbot.libretro.com/nightly
          # if repo has file compression
          compression: zip
        # a secondary repo to use i.e. for not found in the main cores
        secondary:
          type: github
          url: https://github.com/sergystepanov/libretro-spiegel/blob/main
          compression: zip
      # Libretro core configuration
      # ...
      # Available config params:
      #   - altRepo (bool) prioritize secondary repo as the download source
      #   ...
      list:
        # ...
        n64:
          lib: mupen64plus_next_libretro
          altRepo: true
          # ...
```
