### ISSUE TITLE
Does the project support PSP games?

### ISSUE THREAD

**Issue by zslliu** [giongto35/cloud-game#458]
I tried copying the ppsspp_libretro.dll core from RetroArch to the cores folder and added the game rom, however, the game did not run successfully and I found these errors. I can't find the cause of the error.
![Snipaste_2024-06-12_17-23-42](https://github.com/giongto35/cloud-game/assets/36098473/891ba1ff-3e01-4066-b17b-06f8459cb32e)

**Comment by sergystepanov** [comment]
No, it is not supported now (won't be supported), but was tested and was working some time ago. Probably, they changed something in the core.
I have this error:
![image](https://github.com/giongto35/cloud-game/assets/846874/8411b931-531f-4bb4-a0ef-1d9cc2fae48b)
My config:
```yaml
        psp:
          lib: ppsspp_libretro
          roms: [ "iso" ]
          folder: psp
          isGlAllowed: true
          vfr: true
          usesLibCo: true
#          hacks:
#            - skip_hw_context_destroy
          options:
#            "ppsspp_software_rendering": enabled
            "ppsspp_backend": "opengl"
#            "ppsspp_internal_resolution": 480x272
```
